In [1]:
import numpy as np
import pandas as pd

In [7]:
sillyfilepath = "../data/raw/19_06_23_targets_chm51-1147.xlsx"

In [21]:
def get_norm_target_data(sillyfilepath):
    raw_data = pd.read_excel(sillyfilepath, header = 2)
    new_data = raw_data.drop(columns  = ['BAR-CODE', 'comment1', 'comment2', 'comment3', 'Gender', 'Age'])
    new_data.columns = ["label", "ph", "ph_a>6.5", "ph_a>7", "sg", "sg_a", "pro", "pro_a>0.066", "pro_a>0.033", "pro_a>0", "glu", "glu_a", "ket", "ket_a", "bil", "bil_a", "urg", "urg_a", "mucus", "mucus_a", "bact", "bact_a", "ylc", "ylc_a", "sperm", "sperm_a"]
    return new_data

In [22]:
get_norm_target_data(sillyfilepath)

,label,ph,ph_a>6.5,ph_a>7,sg,sg_a,pro,pro_a>0.066,pro_a>0.033,pro_a>0,...,urg,urg_a,mucus,mucus_a,bact,bact_a,ylc,ylc_a,sperm,sperm_a
0,Chm0051,5.0,0.0,0.0,1.025,NaN,0.066,0.0,1.0,1.0,...,-,0.0,-,0.0,-,0.0,-,0.0,-,0.0
1,Chm0052,5.0,0.0,0.0,1.025,NaN,0.033,0.0,0.0,1.0,...,-,0.0,-,0.0,-,0.0,-,0.0,-,0.0
2,Chm0053,6.0,0.0,0.0,1.02,NaN,0,0.0,0.0,0.0,...,-,0.0,-,0.0,-,0.0,-,0.0,-,0.0
3,Chm0054,5.0,0.0,0.0,1.025,NaN,0,0.0,0.0,0.0,...,-,0.0,+,1.0,-,0.0,-,0.0,-,0.0
4,Chm0055,7.0,1.0,0.0,??,NaN,0,0.0,0.0,0.0,...,-,0.0,-,0.0,-,0.0,-,0.0,-,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1069,Chm1168,6.0,0.0,0.0,1010,NaN,0.132,1.0,1.0,1.0,...,0,0.0,0,0.0,++,1.0,0,0.0,0,0.0
1070,Chm1169,5.0,0.0,0.0,1020,NaN,0,0.0,0.0,0.0,...,0,0.0,+,1.0,+,1.0,0,0.0,0,0.0
1071,Chm1170,6.0,0.0,0.0,1005,NaN,0.099,1.0,1.0,1.0,...,0,0.0,++,1.0,+++,1.0,0,0.0,0,0.0
1072,Chm1173,6.0,0.0,0.0,1025,NaN,0.099,1.0,1.0,1.0,...,0,0.0,++,1.0,+,1.0,0,0.0,0,0.0
1073,Chm1174,5.0,0.0,0.0,1025,NaN,0,0.0,0.0,0.0,...,0,0.0,0,0.0,++,1.0,0,0.0,0,0.0